author: DomanoSV
description: Flatlands world generator.
name: FlatlandsBuilder
version: 0.8.0-R1.0
main: net.dkebnh.bukkit.FlatlandsBuilder.FlatlandsBuilder
load: STARTUP
url: http://www.dkebnh.net/
commands:
    flb:
        description: Informs player of FlatlandsBuilder version.
        usage: /flb help for more information.
        aliases: [fb]
    flbe:
        description: Informs player of FlatlandsBuilder version.
        usage: /flb help for more information.
        aliases: [fbe]
    flbw:
        description: Informs player of FlatlandsBuilder version.
        usage: /flb help for more information.
        aliases: [fbw]