author: DomanoSV
description: All new FlatlandsBuilder flatlands world generator.
name: FlatlandsBuilder
version: 0.8.5-R2.0
main: net.dkebnh.bukkit.FlatlandsBuilder.FlatlandsBuilder
load: STARTUP
url: http://www.dkebnh.net/
commands:
    flb:
        description: Default plugin commands.
        usage: /flb help for more information.
        aliases: [fb]
    flbd:
        description: Sets plugin default configuration settings.
        usage: /flbd help for more information.
        aliases: [fbd]
    flbw:
        description: Plugin Command Wizzard.
        usage: /flbw help for more information.
        aliases: [fbw]
